defaults:
  - model: multi_task
  - data: default

data:
  _target_: app.data.SaliconDataset
  path: data/filtered_data
  sampling_strategy: "random"
  dataloader:
    _target_: torch.utils.data.DataLoader
    _partial_: true
    shuffle: true
    batch_size: 64
    num_workers: 8
    persistent_workers: true
    pin_memory: true

model:
  optimizer:
    lr: 1e-3
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: true
    patience: 7
    min_lr: 1e-6

trainer:
  _target_: lightning.Trainer
  max_epochs: 100
  callbacks:
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val/macro_accuracy
      patience: 20
      mode: max
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      monitor: val/macro_accuracy
      save_top_k: 1
      mode: max
  # logger:
  #   _target_: lightning.pytorch.loggers.WandbLogger
  #   project: "salchartqa-attack"
  #   log_model: false
  benchmark: true
  enable_progress_bar: false
